# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c44e21841104e1da7528b989a97bb5896ec0af955a53fff3399a2d251a29242330b6640cee236929856a1985ad763c03ecba5e2d9a2b7dfd45e0375ee1f9ff5a

test:
  secret_key_base: 312aaede2249fac04e9fbe8dd9c479ecdc1b10eb4a99840625fffbcc611e9f1a9ab898246979d2e92b9ba6c2e6b6df5b749d7297ab702e0daeefcd503816a26b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
